# ใช้ PHP 8.3 เวอร์ชันล่าสุดพร้อม FPM
FROM php:8.3-fpm

# ติดตั้ง extension ที่จำเป็น
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    git \
    curl \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd \
    && docker-php-ext-install mysqli pdo pdo_mysql

# ตั้ง working directory
WORKDIR /var/www/html

# คัดลอก source code, vendor, และไฟล์ .env
COPY ./www /var/www/html
COPY ./vendor /var/www/html/vendor
COPY ./.env /var/www/html/.env
