services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - "60001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - theerasan-network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - theerasan-network

  php:
    container_name: php
    build:
      context: .
      dockerfile: dockerfile-php
    restart: always
    volumes:
      - ./www:/var/www/html
    working_dir: /var/www/html
    networks:
      - theerasan-network      

  nginx:
    container_name: nginx_php
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www/html
    depends_on:
      - php
    networks:
      - theerasan-network

volumes:
  database_data:

networks:
  theerasan-network:
    driver: bridge
